### ISSUE TITLE
Command "erc20" not found.

### ISSUE THREAD

**Issue by SatYan14** [coti-io/coti-sdk-typescript#2]
I may have missed a step but it appears that no "scripts" exists for the ```yarn erc20```
 in the package.json : 
```
"scripts": {
    "prepare": "tsc",
    "build": "tsc"
  }
```

**Comment by gmesika-coti** [comment]
@SatYan14 the erc20 is available in the https://github.com/coti-io/coti-sdk-typescript-examples
did you happen to find documentation that is pointing to the sdk repository instead of the examples repository?

**Comment by gmesika-coti** [comment]
documentation fix done in e6eb633b323a2c7d0a90e5956d3f0ea1cec2a239
